package com.tahoecn.bo.common.enums;

/**
 * 指标CODE枚举
 *
 * @author panglx
 */
public enum QuotaCodeEnum {
    FLOOR_HIGH("FLOOR_HIGH_ATTR", "层高属性"),
    PROPERTY_RIGHT("PROPERTY_RIGHT_ATTR", "产权属性"),
    REFINED_DECORATION("REFINED_DECORATION_ATTR", "精装属性"),
    TOTAL_BUILDING_AREA("TOTAL_BUILDING_AREA", "总建筑面积"),
    ABOVE_GROUND_TOTAL_BUILDING_AREA("ABOVE_GROUND_TOTAL_BUILDING_AREA", "地上总建筑面积"),
    UNDER_GROUND_TOTAL_BUILDING_AREA("UNDER_GROUND_TOTAL_BUILDING_AREA", "地下总建筑面积"),
    TOTAL_REAL_BUILDING_AREA("TOTAL_REAL_BUILDING_AREA", "总实际建筑面积"),
    ABOVE_GROUND_REAL_BUILDING_AREA("ABOVE_GROUND_REAL_BUILDING_AREA", "地上实际建筑面积"),
    UNDER_GROUND_REAL_BUILDING_AREA("UNDER_GROUND_REAL_BUILDING_AREA", "地下实际建筑面积"),
    TOTAL_CAN_RENT_SALE_AREA("TOTAL_CAN_RENT_SALE_AREA", "总可租售面积"),
    ABOVE_GROUND_CAN_RENT_SALE_AREA("ABOVE_GROUND_CAN_RENT_SALE_AREA", "地上可租售面积"),
    UNDER_GROUND_CAN_RENT_SALE_AREA("UNDER_GROUND_CAN_RENT_SALE_AREA", "地下可租售面积"),
    TOTAL_CAN_SALE_AREA("TOTAL_CAN_SALE_AREA", "总可售面积"),
    ABOVE_GROUND_CAN_SALE_AREA("ABOVE_GROUND_CAN_SALE_AREA", "地上可售面积"),
    UNDER_GROUND_CAN_SALE_AREA("UNDER_GROUND_CAN_SALE_AREA", "地下可售面积"),
    TOTAL_CAN_RENT_AREA("TOTAL_CAN_RENT_AREA", "总可租面积"),
    ABOVE_GROUND_CAN_RENT_AREA("ABOVE_GROUND_CAN_RENT_AREA", "地上可租面积"),
    UNDER_GROUND_CAN_RENT_AREA("UNDER_GROUND_CAN_RENT_AREA", "地下可租面积"),
    TOTAL_CAN_NOT_RENT_SALE_AREA("TOTAL_CAN_NOT_RENT_SALE_AREA", "总非可租售面积"),
    ABOVE_GROUND_CAN_NOT_RENT_SALE_AREA("ABOVE_GROUND_CAN_NOT_RENT_SALE_AREA", "地上非可租售面积"),
    UNDER_GROUND_CAN_NOT_RENT_SALE_AREA("UNDER_GROUND_CAN_NOT_RENT_SALE_AREA", "地下非可租售面积"),
    TOTAL_GIVE_AREA("TOTAL_GIVE_AREA", "总赠送面积"),
    ABOVE_GROUND_GIVE_AREA("ABOVE_GROUND_GIVE_AREA", "地上赠送面积"),
    UNDER_GROUND_GIVE_AREA("UNDER_GROUND_GIVE_AREA", "地下赠送面积"),
    SINGLE_LAND_COVER_AREA("SINGLE_LAND_COVER_AREA", "单体占地面积"),
    BATCH_REFINE_INNER_SET_AREA("BATCH_REFINE_INNER_SET_AREA", "批量精装修套内面积"),
    TYPICAL_HOUSE_REFINE_INNER_SET_AREA("TYPICAL_HOUSE_REFINE_INNER_SET_AREA", "典型户型精装修套内面积"),
    STANDARD_FLOOR_REFINE_AREA("STANDARD_FLOOR_REFINE_AREA", "标准层精装修面积"),
    PUBLIC_REGION_REFINE_AREA("PUBLIC_REGION_REFINE_AREA", "公区精装修面积"),
    REFINE_MAP_REAL_BUILDING_AREA("REFINE_MAP_REAL_BUILDING_AREA", "精装修对应实际建筑面积"),
    REFINE_HOUSE_COUNT("REFINE_HOUSE_COUNT", "精装修户数"),
    TOTAL_USE_AREA("TOTAL_USE_AREA", "总用地面积"),
    BUILD_LAND_USE_AREA("BUILD_LAND_USE_AREA", "建设用地面积"),
    TOTAL_CALC_VOLUME_BUILDING_AREA("TOTAL_CALC_VOLUME_BUILDING_AREA", "总计容面积"),
    ABOVE_GROUND_CALC_VOLUME_AREA("ABOVE_GROUND_CALC_VOLUME_AREA", "地上计容面积"),
    UNDER_GROUND_CALC_VOLUME_AREA("UNDER_GROUND_CALC_VOLUME_AREA", "地下计容面积"),
    HOUSE_ABOVE_GROUND_BUILDING_AREA("HOUSE_ABOVE_GROUND_BUILDING_AREA", "住宅地上建筑面积"),
    POLICY_HOUSE_BUILDING_AREA("POLICY_HOUSE_BUILDING_AREA", "政策房建筑面积"),
    COMPLETE_BUSINESS_BUILDING_AREA("COMPLETE_BUSINESS_BUILDING_AREA", "配套商业建筑面积"),
    OTHER_COMPLETE_BUILDING_AREA("OTHER_COMPLETE_BUILDING_AREA", "其他配建建筑面积"),
    OWNER_PROPERT_BUILDING_AREA("OWNER_PROPERT_BUILDING_AREA", "自持物业建筑面积"),
    OVERHEAD_REFUGE_CHANGE_FLOOR_AREA("OVERHEAD_REFUGE_CHANGE_FLOOR_AREA", "架空层\\避难层\\转换层建筑面积"),
    BASE_FLOOR_AREA("BASE_FLOOR_AREA", "基底面积"),
    SIMPLE_CAR_PARKING_PLATE_COUNT("SIMPLE_CAR_PARKING_PLATE_COUNT", "车位数"),
    PRODUCT_PRICE("PRODUCT_PRICE", "货值"),
    AVERAGE_PRICE("AVERAGE_PRICE", "均价"),
    BUILDING_LAND_COVER_AREA("BUILDING_LAND_COVER_AREA", "建筑占地面积"),
    PERSON_PROTECT_AREA("PERSON_PROTECT_AREA", "人防面积"),
    NOT_PERSON_PROTECT_AREA("NOT_PERSON_PROTECT_AREA", "非人防面积"),
    CHANGE_PLACE_PERSON_PROTECT_AREA("CHANGE_PLACE_PERSON_PROTECT_AREA", "易地人防面积"),
    CHANGE_PLACE_GREEN_LAND_AREA("CHANGE_PLACE_GREEN_LAND_AREA", "易地绿地面积"),
    TAKE_BY_GREEN_LAND_AREA("TAKE_BY_GREEN_LAND_AREA", "代征绿地面积"),
    TAKE_BY_ROAD_LAND_AREA("TAKE_BY_ROAD_LAND_AREA", "代征道路面积"),
    TAKE_BY_HARD_LANDSCAPE_AREA("TAKE_BY_HARD_LANDSCAPE_AREA", "代征硬景面积"),
    INNER_REGION_HARD_LANDSCAPE_AREA("INNER_REGION_HARD_LANDSCAPE_AREA", "区内硬景面积"),
    TAKE_BY_SOFT_LANDSCAPE_AREA("TAKE_BY_SOFT_LANDSCAPE_AREA", "代征软景面积"),
    INNER_REGION_SOFT_LANDSCAPE_AREA("INNER_REGION_SOFT_LANDSCAPE_AREA", "区内软景面积"),
    ;

    private String key;

    private String value;

    QuotaCodeEnum(String key, String value) {
        this.key = key;
        this.value = value;
    }

    public String getKey() {
        return key;
    }

    public String getValue() {
        return value;
    }

    public static QuotaCodeEnum getByKey(String key) {
        for (QuotaCodeEnum quotaCodeEnum : values()) {
            if (quotaCodeEnum.getKey().equals(key)) {
                return quotaCodeEnum;
            }
        }
        return null;
    }

}
